#!/bin/bash
    #	-fn '-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-u' \

dmenu_run \
    -fn "Liberation Mono-12:bold" \
	-fn '-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-u' \
	-q \
	-i \
	-l 0 \
	-x 0 \
	-y 731 \
	-h 20 \
	-w 1366 \ 
	-nf "#ebdbb2" \
	-nb "#cc241d" \
	-sb "#ebdbb2" \
	-sf "#cc241d" \
