#!/bin/bash
    #	-fn '-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-u' \

dmenu_run \
    -fn "Ohsnap-10:normal" \
    -q \
    -i \
    -l 0 \
	-x 10 \
	-y 10 \
	-h 20 \
    -w 1345 \
	-nb \#141413 \
	-nf \#aeee00 \
	-sb \#242321 \
	-sf \#ff2c4b
